[package]
name = "msp430"
version = "0.1.0"
authors = ["teacher <teacher@cromulence.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scan_fmt = "0.2.5"
